name: cleanly_architected_core
description: A flutter project to help set up clean architecture with less boilerplate.
version: 0.0.2
repository: https://github.com/moseskarunia/cleanly-architected

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: "^1.2.5"
  meta: "^1.2.4"
  dartz: "^0.9.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 4.1.1

flutter:
