name: cleanly_architected_core
description: A dart project to help set up clean architecture with less boilerplate.
version: 0.0.7
repository: https://github.com/moseskarunia/cleanly-architected/tree/master/packages/cleanly_architected_core

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  meta: ^1.2.4
  dartz: ^0.9.1

dev_dependencies:
  test: ^1.14.6
  mockito: ^4.1.1
  coverage: ^0.14.1