name: cleanly_architected_state_manager_bloc
description: State manager for cleanly architected using bloc / cubit. This way, you can use the core with other state manager as well.
version: 0.0.9
repository: https://github.com/moseskarunia/cleanly-architected/tree/master/packages/cleanly_architected_state_manager_bloc

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.1
  cleanly_architected_core: ^0.0.13
  dartz: ^0.9.1
  equatable: ^1.2.5
  meta: ^1.2.4

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.14.6
  bloc_test: ^7.1.0
  coverage: ^0.14.1
