name: cleanly_architected_state_manager_bloc
description: State manager for cleanly architected using bloc / cubit.
version: 0.0.1
repository: https://github.com/moseskarunia/cleanly-architected

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bloc: ^6.1.1
  cleanly_architected_core: ^0.0.5
  copy_with_extension: ^1.4.0
  dartz: ^0.9.1
  equatable: ^1.2.5
  meta: ^1.2.4

dev_dependencies:
  mockito: ^4.1.1
  test: ^1.14.6
  bloc_test: ^7.1.0
  copy_with_extension_gen: ^1.4.0
  build_runner: ^1.10.9
  coverage: ^0.14.1
