name: cleanly_architected_state_manager_bloc
description: State manager for cleanly architected using bloc / cubit.
version: 0.0.1
repository: https://github.com/moseskarunia/cleanly-architected

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  equatable: ^1.2.5
  meta: ^1.2.4
  dartz: ^0.9.1
  cleanly_architected_core: ^0.0.5
  bloc: ^6.1.1

dev_dependencies:
  test: ^1.14.6
  mockito: ^4.1.1
