name: cleanly_architected_state_manager_bloc

on:
  push:
    branches: [master]
    paths:
      - "packages/cleanly_architected_state_manager_bloc/**"
      - ".github/workflows/cleanly_architected_state_manager_bloc.yaml"
  pull_request:
    paths:
      - "packages/cleanly_architected_state_manager_bloc/**"
      - ".github/workflows/cleanly_architected_state_manager_bloc.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/cleanly_architected_state_manager_bloc
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.10.0

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Generate files
        run: pub run build_runner build --delete-conflicting-outputs
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Test
        run: dart test --coverage=coverage
      - name: Generate Coverage Report
        run: pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib && pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$'
      - name: Check Code Coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Dry Run Publish to Pub Dev
        run: pub publish --dry-run
